version: 1.0.{build}

image: Visual Studio 2017 Preview

init:
- ps: ''
install:
- ps: choco install miniconda3
- ps: refreshenv
- ps: conda3 --info
- ps: conda --info
# maybe it is not conda but conda3

build_script:
# Create conda enviroment
- ps: conda create -q -n test-environment python=2.7
- ps: activate test-environment
- ps: conda install cmake
# info on python executables
- ps: python --version
- cmd: pip install setuptools
- cmd: pip install -r python\requirements.txt
- cmd: python -m pip install --upgrade pip
- cmd: cd C:\projects\PyMesh
- cmd: .\setup.py build
- cmd: .\setup.py install --user --prefix=
- cmd: python -c "import pymesh; pymesh.test()"
