version: 1.0.{build}

image: Visual Studio 2017 Preview

init:
- ps: ''
install:
- ps: choco install miniconda3 
- ps: choco install vcpython27

build_script:
# Create conda enviroment
- cmd: conda create -q -n test-environment python=2.7
- cmd: activate test-environment
- cmd: conda install cmake
# info on python executables
- cmd: python --version
- cmd: pip install setuptools
- cmd: pip install -r python\requirements.txt
- cmd: python -m pip install --upgrade pip
- cmd: cd C:\projects\PyMesh
- cmd: .\setup.py build
- cmd: .\setup.py install --user --prefix=
- cmd: python -c "import pymesh; pymesh.test()"
